### ISSUE TITLE
build error in libfs/tests

### ISSUE THREAD

**Issue by juno-kim** [ut-osa/strata#13]
When I run `make` in libfs/tests, I get the following error.

../src/storage/spdk//libspdk.so: undefined reference to `pci_map_resource'
../src/storage/spdk//libspdk.so: undefined reference to `uuid_unparse_lower'
../src/storage/spdk//libspdk.so: undefined reference to `numa_available'
../src/storage/spdk//libspdk.so: undefined reference to `get_mempolicy'
../src/storage/spdk//libspdk.so: undefined reference to `uuid_parse'
../src/storage/spdk//libspdk.so: undefined reference to `rte_pci_addr_parse'
../src/storage/spdk//libspdk.so: undefined reference to `numa_set_localalloc'
../src/storage/spdk//libspdk.so: undefined reference to `rte_pci_addr_cmp'
../src/storage/spdk//libspdk.so: undefined reference to `numa_bitmask_free'
../src/storage/spdk//libspdk.so: undefined reference to `set_mempolicy'
../src/storage/spdk//libspdk.so: undefined reference to `numa_allocate_nodemask'
../src/storage/spdk//libspdk.so: undefined reference to `rte_pci_device_name'
../src/storage/spdk//libspdk.so: undefined reference to `pci_unmap_resource'
../src/storage/spdk//libspdk.so: undefined reference to `uuid_compare'
../src/storage/spdk//libspdk.so: undefined reference to `uuid_generate'
../src/storage/spdk//libspdk.so: undefined reference to `numa_set_preferred'
collect2: error: ld returned 1 exit status
Makefile:82: recipe for target 'iotest' failed
make: *** [iotest] Error 1

Adding -lnuma, -luuid does not solve the problem. Can anyone help this?

**Comment by zbhhbzzbh** [comment]
did you ever tamper the Makefile anywhere?

**Comment by juno-kim** [comment]
Solved. Yes, I modified the Makefile and that was the problem.
